# -*- coding: utf-8 -*-
"""IE6520 Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DIl4mTzV0ltr1ca_vSf05jJhnE3bFYqJ
"""

# Final stable toy experiment (active querying + pseudo-label ablation)
# Tuned to produce consistent and meaningful results

import numpy as np
import matplotlib.pyplot as plt

# ====== Settings ======
d = 5
T = 500
n_seeds = 10

# ====== Environment ======
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sample_action():
    return np.random.randn(d)

def run_method(mode, theta_star, threshold=1.0):
    regrets = []
    queries = []

    for seed in range(n_seeds):
        np.random.seed(seed)
        theta_hat = np.zeros(d)
        lr = 0.01  # smaller learning rate for stability

        total_regret = 0
        q = 0

        for t in range(T):
            x1 = sample_action()
            x2 = sample_action()

            r1 = np.dot(theta_star, x1)
            r2 = np.dot(theta_star, x2)
            optimal = max(r1, r2)

            pred_diff = np.dot(theta_hat, x1 - x2)

            # ===== Mode logic =====
            if mode == "full":
                prob = sigmoid(r1 - r2)
                o = 1 if np.random.rand() < prob else -1
                q += 1

            elif mode == "active_pl":
                if abs(pred_diff) < threshold:
                    prob = sigmoid(r1 - r2)
                    o = 1 if np.random.rand() < prob else -1
                    q += 1
                else:
                    o = 1 if pred_diff > 0 else -1

            elif mode == "active_no_pl":
                if abs(pred_diff) < threshold:
                    prob = sigmoid(r1 - r2)
                    o = 1 if np.random.rand() < prob else -1
                    q += 1
                else:
                    chosen_reward = r1 if pred_diff > 0 else r2
                    total_regret += (optimal - chosen_reward)
                    continue

            # ===== Update =====
            grad = o * (x1 - x2)
            theta_hat += lr * grad

            # ===== Evaluate =====
            chosen_reward = r1 if np.dot(theta_hat, x1) > np.dot(theta_hat, x2) else r2
            total_regret += (optimal - chosen_reward)

        regrets.append(total_regret)
        queries.append(q)

    return np.mean(regrets), np.mean(queries)

# ====== Run experiment ======

np.random.seed(42)
theta_star = np.random.randn(d)

thresholds = [0.5, 1.0, 2.0, 3.0]

full_regret, full_query = run_method("full", theta_star)

results_active = []
results_no_pl = []

for th in thresholds:
    reg1, q1 = run_method("active_pl", theta_star, threshold=th)
    reg2, q2 = run_method("active_no_pl", theta_star, threshold=th)

    results_active.append((reg1, q1))
    results_no_pl.append((reg2, q2))

# ====== Plot ======

plt.figure()

# Full baseline
plt.scatter(full_query, full_regret, marker="X", s=120, label="Full Query")

# Active + pseudo-label
qs = [x[1] for x in results_active]
rs = [x[0] for x in results_active]
plt.plot(qs, rs, marker="o", linewidth=2, label="Active + Pseudo-label")

# Active without pseudo-label
qs2 = [x[1] for x in results_no_pl]
rs2 = [x[0] for x in results_no_pl]
plt.plot(qs2, rs2, marker="s", linestyle="--", linewidth=2, label="Active (no pseudo-label)")

plt.xlabel("Number of Queries")
plt.ylabel("Final Regret")
plt.title("Active Querying vs Full Query (Toy Experiment)")
plt.legend()
plt.grid()

plt.show()

# ====== Print results ======

print("=== Full Query ===")
print(f"Regret: {full_regret:.2f}, Queries: {full_query:.1f}")

for i, th in enumerate(thresholds):
    print(f"\n=== Threshold {th} ===")
    print(f"Active + PL -> Regret: {results_active[i][0]:.2f}, Queries: {results_active[i][1]:.1f}")
    print(f"Active (no PL) -> Regret: {results_no_pl[i][0]:.2f}, Queries: {results_no_pl[i][1]:.1f}")



# Mini DPO-style experiment with active querying and pseudo-labels
# Runs on CPU (Colab compatible)

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# ====== 1. Settings ======
d = 5
T = 500
n_seeds = 5
threshold = 1.0
lr = 0.01

# ====== 2. Model ======
class SimpleModel(nn.Module):
    def __init__(self, d):
        super().__init__()
        self.linear = nn.Linear(d, 1)

    def forward(self, x):
        return self.linear(x).squeeze(-1)

# ====== 3. Environment ======
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sample_action():
    return np.random.randn(d)

def sample_preference(x1, x2, theta_star):
    r1 = np.dot(theta_star, x1)
    r2 = np.dot(theta_star, x2)
    prob = sigmoid(r1 - r2)
    return 1 if np.random.rand() < prob else -1

# ====== 4. Training function ======
def run(mode):
    regrets = []
    queries = []

    for seed in range(n_seeds):
        np.random.seed(seed)
        torch.manual_seed(seed)

        theta_star = np.random.randn(d)

        model = SimpleModel(d)
        optimizer = optim.SGD(model.parameters(), lr=lr)

        total_regret = 0
        q = 0

        for t in range(T):
            x1 = sample_action()
            x2 = sample_action()

            x1_t = torch.tensor(x1, dtype=torch.float32)
            x2_t = torch.tensor(x2, dtype=torch.float32)

            r1 = np.dot(theta_star, x1)
            r2 = np.dot(theta_star, x2)
            optimal = max(r1, r2)

            s1 = model(x1_t)
            s2 = model(x2_t)
            diff = s1 - s2

            # ===== Mode logic =====
            if mode == "full":
                o = sample_preference(x1, x2, theta_star)
                q += 1

            elif mode == "active_pl":
                if abs(diff.item()) < threshold:
                    o = sample_preference(x1, x2, theta_star)
                    q += 1
                else:
                    o = 1 if diff.item() > 0 else -1

            elif mode == "active_no_pl":
                if abs(diff.item()) < threshold:
                    o = sample_preference(x1, x2, theta_star)
                    q += 1
                else:
                    chosen = r1 if diff.item() > 0 else r2
                    total_regret += (optimal - chosen)
                    continue

            # ===== DPO-style loss =====
            label = torch.tensor(o, dtype=torch.float32)
            loss = -torch.log(torch.sigmoid(label * (s1 - s2)))

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            # ===== Evaluate =====
            with torch.no_grad():
                s1_eval = model(x1_t)
                s2_eval = model(x2_t)
                chosen = r1 if s1_eval > s2_eval else r2

            total_regret += (optimal - chosen)

        regrets.append(total_regret)
        queries.append(q)

    return np.mean(regrets), np.mean(queries)

# ====== 5. Run ======
modes = ["full", "active_pl", "active_no_pl"]
results = {}

for m in modes:
    reg, q = run(m)
    results[m] = (reg, q)

# ====== 6. Plot ======
plt.figure()

plt.scatter(results["full"][1], results["full"][0], label="Full", marker="X", s=120)
plt.scatter(results["active_pl"][1], results["active_pl"][0], label="Active + PL", s=80)
plt.scatter(results["active_no_pl"][1], results["active_no_pl"][0], label="Active (no PL)", s=80)

plt.xlabel("Number of Queries")
plt.ylabel("Final Regret")
plt.title("Mini DPO-style Experiment")
plt.legend()
plt.grid()

plt.show()

# ====== 7. Print ======
for k, v in results.items():
    print(k, "-> Regret:", round(v[0],2), " Queries:", round(v[1],1))



# =========================================
# 1. Toy Bandit Experiment
# =========================================

import numpy as np
import matplotlib.pyplot as plt

d = 5
T = 500
n_seeds = 10

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sample_action():
    return np.random.randn(d)

def run_method(mode, theta_star, threshold=1.0):
    regrets = []
    queries = []

    for seed in range(n_seeds):
        np.random.seed(seed)
        theta_hat = np.zeros(d)
        lr = 0.01

        total_regret = 0
        q = 0

        for t in range(T):
            x1 = sample_action()
            x2 = sample_action()

            r1 = np.dot(theta_star, x1)
            r2 = np.dot(theta_star, x2)
            optimal = max(r1, r2)

            pred_diff = np.dot(theta_hat, x1 - x2)

            if mode == "full":
                prob = sigmoid(r1 - r2)
                o = 1 if np.random.rand() < prob else -1
                q += 1

            elif mode == "active_pl":
                if abs(pred_diff) < threshold:
                    prob = sigmoid(r1 - r2)
                    o = 1 if np.random.rand() < prob else -1
                    q += 1
                else:
                    o = 1 if pred_diff > 0 else -1

            elif mode == "active_no_pl":
                if abs(pred_diff) < threshold:
                    prob = sigmoid(r1 - r2)
                    o = 1 if np.random.rand() < prob else -1
                    q += 1
                else:
                    chosen = r1 if pred_diff > 0 else r2
                    total_regret += (optimal - chosen)
                    continue

            grad = o * (x1 - x2)
            theta_hat += lr * grad

            chosen = r1 if np.dot(theta_hat, x1) > np.dot(theta_hat, x2) else r2
            total_regret += (optimal - chosen)

        regrets.append(total_regret)
        queries.append(q)

    return np.mean(regrets), np.mean(queries)

# Run Toy
np.random.seed(42)
theta_star = np.random.randn(d)
thresholds = [0.5, 1.0, 2.0, 3.0]

full_regret, full_query = run_method("full", theta_star)

results_active = []
results_no_pl = []

for th in thresholds:
    results_active.append(run_method("active_pl", theta_star, th))
    results_no_pl.append(run_method("active_no_pl", theta_star, th))

# Plot Toy
plt.figure()
plt.scatter(full_query, full_regret, marker="X", s=120, label="Full Query")

plt.plot([x[1] for x in results_active],
         [x[0] for x in results_active],
         marker="o", label="Active + PL")

plt.plot([x[1] for x in results_no_pl],
         [x[0] for x in results_no_pl],
         marker="s", linestyle="--", label="Active (no PL)")

plt.xlabel("Number of Queries")
plt.ylabel("Final Regret")
plt.title("Toy: Query vs Regret")
plt.legend()
plt.grid()
plt.show()


# =========================================
# 2. Mini DPO Experiment + Learning Curve
# =========================================

import torch
import torch.nn as nn
import torch.optim as optim

d = 5
T = 500
n_seeds = 5
threshold = 1.0
lr = 0.01

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(d, 1)

    def forward(self, x):
        return self.linear(x).squeeze(-1)

def sample_pref(x1, x2, theta):
    r1 = np.dot(theta, x1)
    r2 = np.dot(theta, x2)
    prob = 1 / (1 + np.exp(-(r1 - r2)))
    return 1 if np.random.rand() < prob else -1

def run(mode):
    final_regrets = []
    queries = []
    histories = []

    for seed in range(n_seeds):
        np.random.seed(seed)
        torch.manual_seed(seed)

        theta_star = np.random.randn(d)
        model = Model()
        opt = optim.SGD(model.parameters(), lr=lr)

        total_regret = 0
        q = 0
        history = []

        for t in range(T):
            x1 = sample_action()
            x2 = sample_action()

            x1_t = torch.tensor(x1, dtype=torch.float32)
            x2_t = torch.tensor(x2, dtype=torch.float32)

            r1 = np.dot(theta_star, x1)
            r2 = np.dot(theta_star, x2)
            optimal = max(r1, r2)

            s1 = model(x1_t)
            s2 = model(x2_t)
            diff = s1 - s2

            if mode == "full":
                o = sample_pref(x1, x2, theta_star)
                q += 1

            elif mode == "active_pl":
                if abs(diff.item()) < threshold:
                    o = sample_pref(x1, x2, theta_star)
                    q += 1
                else:
                    o = 1 if diff.item() > 0 else -1

            elif mode == "active_no_pl":
                if abs(diff.item()) < threshold:
                    o = sample_pref(x1, x2, theta_star)
                    q += 1
                else:
                    chosen = r1 if diff.item() > 0 else r2
                    total_regret += (optimal - chosen)
                    history.append(total_regret)
                    continue

            loss = -torch.log(torch.sigmoid(torch.tensor(o, dtype=torch.float32) * (s1 - s2)))

            opt.zero_grad()
            loss.backward()
            opt.step()

            with torch.no_grad():
                chosen = r1 if model(x1_t) > model(x2_t) else r2

            total_regret += (optimal - chosen)
            history.append(total_regret)

        final_regrets.append(total_regret)
        queries.append(q)
        histories.append(history)

    return np.mean(final_regrets), np.mean(queries), np.mean(histories, axis=0)


# Run Mini DPO
modes = ["full", "active_pl", "active_no_pl"]
results = {}
histories = {}

for m in modes:
    reg, q, hist = run(m)
    results[m] = (reg, q)
    histories[m] = hist

# Plot 1: Query vs Regret
plt.figure()
for m in modes:
    plt.scatter(results[m][1], results[m][0], label=m)

plt.xlabel("Number of Queries")
plt.ylabel("Final Regret")
plt.title("Mini DPO: Query Efficiency")
plt.legend()
plt.grid()
plt.show()

# Plot 2: Learning Curve (핵심 ⭐)
plt.figure()
for m in modes:
    plt.plot(histories[m], label=m)

plt.xlabel("Iterations")
plt.ylabel("Cumulative Regret")
plt.title("Learning Curve (Iterations)")
plt.legend()
plt.grid()
plt.show()

# =========================================
# Mini DPO with "Accuracy" (correct decision rate)
# =========================================

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

d = 5
T = 500
n_seeds = 5
threshold = 0.3
lr = 0.01

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(d, 1)

    def forward(self, x):
        return self.linear(x).squeeze(-1)

def sample_action():
    return np.random.randn(d)

def sample_pref(x1, x2, theta):
    r1 = np.dot(theta, x1)
    r2 = np.dot(theta, x2)
    prob = 1 / (1 + np.exp(-(r1 - r2)))
    return 1 if np.random.rand() < prob else -1

def run(mode):
    histories = []

    for seed in range(n_seeds):
        np.random.seed(seed)
        torch.manual_seed(seed)

        theta_star = np.random.randn(d)
        model = Model()
        opt = optim.SGD(model.parameters(), lr=lr)

        correct_count = 0
        acc_history = []

        for t in range(T):
            x1 = sample_action()
            x2 = sample_action()

            x1_t = torch.tensor(x1, dtype=torch.float32)
            x2_t = torch.tensor(x2, dtype=torch.float32)

            r1 = np.dot(theta_star, x1)
            r2 = np.dot(theta_star, x2)

            optimal = 1 if r1 > r2 else -1

            s1 = model(x1_t)
            s2 = model(x2_t)
            diff = s1 - s2

            # ===== Mode =====
            if mode == "full":
                o = sample_pref(x1, x2, theta_star)

            elif mode == "active_pl":
                if abs(diff.item()) < threshold:
                    o = sample_pref(x1, x2, theta_star)
                else:
                    o = 1 if diff.item() > 0 else -1

            elif mode == "active_no_pl":
                if abs(diff.item()) < threshold:
                    o = sample_pref(x1, x2, theta_star)
                else:
                    o = 1 if diff.item() > 0 else -1

            # ===== Train =====
            loss = -torch.log(torch.sigmoid(torch.tensor(o, dtype=torch.float32) * (s1 - s2)))

            opt.zero_grad()
            loss.backward()
            opt.step()

            # ===== Prediction =====
            pred = 1 if model(x1_t) > model(x2_t) else -1

            if pred == optimal:
                correct_count += 1

            acc_history.append(correct_count / (t + 1))

        histories.append(acc_history)

    return np.mean(histories, axis=0)


# Run
modes = ["full", "active_pl", "active_no_pl"]
histories = {}

for m in modes:
    histories[m] = run(m)

# Plot (이게 상대가 원하는 그래프)
plt.figure()

for m in modes:
    plt.plot(histories[m], label=m)

plt.xlabel("Iterations")
plt.ylabel("Accuracy")
plt.title("Learning Curve (Accuracy)")
plt.legend()
plt.grid()

plt.show()

